//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantMVC.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Home {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Home() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RestaurantMVC.Resources.Home", typeof(Home).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When it comes to cooking and the talk falls on India, it is a country with great diversity in this subject..
        /// </summary>
        public static string Abt1 {
            get {
                return ResourceManager.GetString("Abt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are a lot of different cooking traditions from north to south in this adventurous country but when people typically speak Indian, that is what the North Indian chef is thinking of..
        /// </summary>
        public static string Abt2 {
            get {
                return ResourceManager.GetString("Abt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to North Indian has served dishes such as, the ever popular butter chicken, delicious spicy samosa and full-bodied and flavorful naan bread for creamy curry sauce..
        /// </summary>
        public static string Abt3 {
            get {
                return ResourceManager.GetString("Abt3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The north indian adds weight to the authentic flavors and welcomes you to a little distance to the north india in denmark..
        /// </summary>
        public static string Abt4 {
            get {
                return ResourceManager.GetString("Abt4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get In Touch.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string Contact1 {
            get {
                return ResourceManager.GetString("Contact1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string ContactAddress {
            get {
                return ResourceManager.GetString("ContactAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address.
        /// </summary>
        public static string ContactEmail {
            get {
                return ResourceManager.GetString("ContactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Hours.
        /// </summary>
        public static string ContactHours {
            get {
                return ResourceManager.GetString("ContactHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string ContactMsg {
            get {
                return ResourceManager.GetString("ContactMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Name.
        /// </summary>
        public static string ContactName {
            get {
                return ResourceManager.GetString("ContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string ContactSub {
            get {
                return ResourceManager.GetString("ContactSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUR Gallery.
        /// </summary>
        public static string Gallery {
            get {
                return ResourceManager.GetString("Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        public static string lblMonday {
            get {
                return ResourceManager.GetString("lblMonday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        public static string lblSaturday {
            get {
                return ResourceManager.GetString("lblSaturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        public static string lblSunday {
            get {
                return ResourceManager.GetString("lblSunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday To Friday.
        /// </summary>
        public static string lblweekday {
            get {
                return ResourceManager.GetString("lblweekday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday Close.
        /// </summary>
        public static string lblWeekOff {
            get {
                return ResourceManager.GetString("lblWeekOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUR CHEFS.
        /// </summary>
        public static string ManuOurchefs {
            get {
                return ResourceManager.GetString("ManuOurchefs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MENU.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABOUT US.
        /// </summary>
        public static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTACT.
        /// </summary>
        public static string MenuContact {
            get {
                return ResourceManager.GetString("MenuContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GALLERY.
        /// </summary>
        public static string MenuGallary {
            get {
                return ResourceManager.GetString("MenuGallary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOME.
        /// </summary>
        public static string Menuhome {
            get {
                return ResourceManager.GetString("Menuhome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESERVATION.
        /// </summary>
        public static string MenuReser {
            get {
                return ResourceManager.GetString("MenuReser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening Hours.
        /// </summary>
        public static string OpenHours {
            get {
                return ResourceManager.GetString("OpenHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUR MENU.
        /// </summary>
        public static string OurMenu {
            get {
                return ResourceManager.GetString("OurMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Professionals.
        /// </summary>
        public static string OurPro {
            get {
                return ResourceManager.GetString("OurPro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MASTER CHEFS.
        /// </summary>
        public static string OurPro1 {
            get {
                return ResourceManager.GetString("OurPro1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Reservation.
        /// </summary>
        public static string ReservBtn {
            get {
                return ResourceManager.GetString("ReservBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make A.
        /// </summary>
        public static string Rev {
            get {
                return ResourceManager.GetString("Rev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Message.
        /// </summary>
        public static string SendMsgBtn {
            get {
                return ResourceManager.GetString("SendMsgBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Slider1 {
            get {
                return ResourceManager.GetString("Slider1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To The North Indian Restaurant.
        /// </summary>
        public static string Slider1_1 {
            get {
                return ResourceManager.GetString("Slider1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Elegant.
        /// </summary>
        public static string Slider2 {
            get {
                return ResourceManager.GetString("Slider2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The North Indian Restaurant and Takeaway.
        /// </summary>
        public static string Slider2_2 {
            get {
                return ResourceManager.GetString("Slider2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delicious.
        /// </summary>
        public static string Slider3 {
            get {
                return ResourceManager.GetString("Slider3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try Our North Indian.
        /// </summary>
        public static string Slider3_1 {
            get {
                return ResourceManager.GetString("Slider3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spicy Masalas.
        /// </summary>
        public static string Slider3_2 {
            get {
                return ResourceManager.GetString("Slider3_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOOK A TABLE.
        /// </summary>
        public static string SliderBtn {
            get {
                return ResourceManager.GetString("SliderBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testimonials.
        /// </summary>
        public static string Testimo {
            get {
                return ResourceManager.GetString("Testimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What Customers Say.
        /// </summary>
        public static string Testimo1 {
            get {
                return ResourceManager.GetString("Testimo1", resourceCulture);
            }
        }
    }
}
