//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantMVC.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MenuItem {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MenuItem() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RestaurantMVC.Resources.MenuItem", typeof(MenuItem).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homemade delicious Indian chips multicolored..
        /// </summary>
        public static string MenuDec1_1a {
            get {
                return ResourceManager.GetString("MenuDec1_1a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thin Sprede Snacks.
        /// </summary>
        public static string MenuDec1_2 {
            get {
                return ResourceManager.GetString("MenuDec1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samosa with Potatoes, Peas fried, in Spicy Dough.
        /// </summary>
        public static string MenuDec1_3 {
            get {
                return ResourceManager.GetString("MenuDec1_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samosa with Chicken, Peas fried, in Spicy Dough.
        /// </summary>
        public static string MenuDec1_4 {
            get {
                return ResourceManager.GetString("MenuDec1_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onion Rings fried in Spicy Dough.
        /// </summary>
        public static string MenuDec1_5 {
            get {
                return ResourceManager.GetString("MenuDec1_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potatoes fried in spicy dough..
        /// </summary>
        public static string MenuDec1_5a {
            get {
                return ResourceManager.GetString("MenuDec1_5a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chicken fried in Spicy Dough.
        /// </summary>
        public static string MenuDec1_6 {
            get {
                return ResourceManager.GetString("MenuDec1_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to King Prawns fried in Well-Seasoned Dough.
        /// </summary>
        public static string MenuDec1_7 {
            get {
                return ResourceManager.GetString("MenuDec1_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fish fried in spicy dough..
        /// </summary>
        public static string MenuDec1_7a {
            get {
                return ResourceManager.GetString("MenuDec1_7a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chicken thighs marinated In yogurt and tandoori in Spices, served with salad.
        /// </summary>
        public static string MenuDec1_8 {
            get {
                return ResourceManager.GetString("MenuDec1_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homemade Cheese with Butter, Creamy Sauce, Raisins, Coconut, Honey, topped with Nut Mix.
        /// </summary>
        public static string MenuDec10_1 {
            get {
                return ResourceManager.GetString("MenuDec10_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixed Lentils cooked with Cumin, Ginger and Garlic..
        /// </summary>
        public static string MenuDec10_2 {
            get {
                return ResourceManager.GetString("MenuDec10_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homemade Cheese made with Spinach and Spice Dough..
        /// </summary>
        public static string MenuDec10_3 {
            get {
                return ResourceManager.GetString("MenuDec10_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fresh mixed vegetables with curry and tomato sauce..
        /// </summary>
        public static string MenuDec10_4 {
            get {
                return ResourceManager.GetString("MenuDec10_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potatoes with light Curry sauce, Ginger and Garlic..
        /// </summary>
        public static string MenuDec10_5 {
            get {
                return ResourceManager.GetString("MenuDec10_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potatoes, spinach and spices..
        /// </summary>
        public static string MenuDec10_6 {
            get {
                return ResourceManager.GetString("MenuDec10_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potatoes peas, curry sauce and spices..
        /// </summary>
        public static string MenuDec10_7 {
            get {
                return ResourceManager.GetString("MenuDec10_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pepper, Chicken baked in tandoor, Tomato sauce, Chilli, Ginger, Garlic..
        /// </summary>
        public static string MenuDec11_1 {
            get {
                return ResourceManager.GetString("MenuDec11_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pepper, lamb, tomato sauce, chilli, ginger, garlic..
        /// </summary>
        public static string MenuDec11_1a {
            get {
                return ResourceManager.GetString("MenuDec11_1a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pepper, Homemade Cheese, Chilli, Ginger, White log.
        /// </summary>
        public static string MenuDec11_2 {
            get {
                return ResourceManager.GetString("MenuDec11_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fish in mild curry sauce..
        /// </summary>
        public static string MenuDec11_3 {
            get {
                return ResourceManager.GetString("MenuDec11_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curry, cream, almonds, cashews, coriander..
        /// </summary>
        public static string MenuDec11_4 {
            get {
                return ResourceManager.GetString("MenuDec11_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lamb Korma Creamy Lamb with Curry Sauce, Creamy, Nut Mix, Ginger, Butter and Coriander..
        /// </summary>
        public static string MenuDec11_5 {
            get {
                return ResourceManager.GetString("MenuDec11_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curry sauce, cream, almonds, cashews..
        /// </summary>
        public static string MenuDec11_5a {
            get {
                return ResourceManager.GetString("MenuDec11_5a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creamy chicken fillet and curry sauce, Tops with nut mix..
        /// </summary>
        public static string MenuDec11_7 {
            get {
                return ResourceManager.GetString("MenuDec11_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fresh Indian bread baked in Tandoori.
        /// </summary>
        public static string MenuDec12_1 {
            get {
                return ResourceManager.GetString("MenuDec12_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fresh Indian bread with garlic baked in Tandoori..
        /// </summary>
        public static string MenuDec12_2 {
            get {
                return ResourceManager.GetString("MenuDec12_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fresh Indian bread with butter baked in Tandoori..
        /// </summary>
        public static string MenuDec12_3 {
            get {
                return ResourceManager.GetString("MenuDec12_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traditional Indian bread.
        /// </summary>
        public static string MenuDec12_4 {
            get {
                return ResourceManager.GetString("MenuDec12_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dough bun in syrup, classic hot indian dessert,topped with nut mix.
        /// </summary>
        public static string MenuDec13_1 {
            get {
                return ResourceManager.GetString("MenuDec13_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 or 2L.
        /// </summary>
        public static string MenuDec14_9 {
            get {
                return ResourceManager.GetString("MenuDec14_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mango, Mint Chutney, Pickles, Ketchup or Mayo.
        /// </summary>
        public static string MenuDec15_1 {
            get {
                return ResourceManager.GetString("MenuDec15_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chickpeas with curry sauce, 2 pcs. naan bread, pickles chutney,vinegar and red onion.
        /// </summary>
        public static string MenuDec16_1 {
            get {
                return ResourceManager.GetString("MenuDec16_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chickpeas with curry sauce, 2 pcs. Fry Indian wheat flour bread,pickles chutney, vinegar and red onion..
        /// </summary>
        public static string MenuDec16_2 {
            get {
                return ResourceManager.GetString("MenuDec16_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chickpeas with curry sauce, 2 pcs. fry wheat flour bread, pickles chutney, vinegar and red onion.
        /// </summary>
        public static string MenuDec16_3 {
            get {
                return ResourceManager.GetString("MenuDec16_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Butter Chicken, Lamb, Ox, King Prawn, Creamy Chicken, Lamb Korma Creamy.
        /// </summary>
        public static string MenuDec17_1 {
            get {
                return ResourceManager.GetString("MenuDec17_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fried and lightly spiced rice with green peas (For children).
        /// </summary>
        public static string MenuDec18_5 {
            get {
                return ResourceManager.GetString("MenuDec18_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mix Vegetarian, basmati rice, turmeric and coriander.
        /// </summary>
        public static string MenuDec18_5a {
            get {
                return ResourceManager.GetString("MenuDec18_5a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basmati Rice.
        /// </summary>
        public static string MenuDec18_6 {
            get {
                return ResourceManager.GetString("MenuDec18_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incl. Boondi Raita.
        /// </summary>
        public static string MenuDec18_Raita {
            get {
                return ResourceManager.GetString("MenuDec18_Raita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mild Curry Soup With Chicken, Served With 1 Piece Naan Bread.
        /// </summary>
        public static string MenuDec2_1 {
            get {
                return ResourceManager.GetString("MenuDec2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vegetarian Soup With Lentils, Curry Sauce and Spices Served With 1 Piece Naan Bread.
        /// </summary>
        public static string MenuDec2_2 {
            get {
                return ResourceManager.GetString("MenuDec2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomato Soup Mixed with Mild Spices Served With 1 Piece Naan Bread.
        /// </summary>
        public static string MenuDec2_3 {
            get {
                return ResourceManager.GetString("MenuDec2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cucumber, Lettuce, Cherry Tomato, Red Onion, Pepper, Sunflower Seeds, Carrots, Chilli Onion Chicken with Lime Baked Tandoori.
        /// </summary>
        public static string MenuDec3_1 {
            get {
                return ResourceManager.GetString("MenuDec3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cucumber, Salad, Cherry Tomato, Red Onion, Pepper, Sunflower Seeds, Carrot, Olive, Chilli Onion and Lime with Homemade Cottage Cheese.
        /// </summary>
        public static string MenuDec3_2 {
            get {
                return ResourceManager.GetString("MenuDec3_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yogurt with cucumber, tomatoes, potatoes with fresh coriander leaves.
        /// </summary>
        public static string MenuDec4_1 {
            get {
                return ResourceManager.GetString("MenuDec4_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indian Yogurt with Granulated Chickpeas.
        /// </summary>
        public static string MenuDec4_2 {
            get {
                return ResourceManager.GetString("MenuDec4_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indian Fried Basmatirls, Peppers, Almonds, Raisins, Coconut and Indian Spices.
        /// </summary>
        public static string MenuDec4_3 {
            get {
                return ResourceManager.GetString("MenuDec4_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mild Butter Chicken or Creamy Chicken with Rice.
        /// </summary>
        public static string MenuDec6_1 {
            get {
                return ResourceManager.GetString("MenuDec6_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chicken Nuggets Served with French Fries and light Salad.
        /// </summary>
        public static string MenuDec6_2 {
            get {
                return ResourceManager.GetString("MenuDec6_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. fish fillet with french fries..
        /// </summary>
        public static string MenuDec6_3 {
            get {
                return ResourceManager.GetString("MenuDec6_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dried spinach with fresh spices..
        /// </summary>
        public static string MenuDec9_1 {
            get {
                return ResourceManager.GetString("MenuDec9_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starters with sauce.
        /// </summary>
        public static string MenuItem1_1 {
            get {
                return ResourceManager.GetString("MenuItem1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chips.
        /// </summary>
        public static string MenuItem1_1a {
            get {
                return ResourceManager.GetString("MenuItem1_1a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Papadum.
        /// </summary>
        public static string MenuItem1_2 {
            get {
                return ResourceManager.GetString("MenuItem1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veg Samosa.
        /// </summary>
        public static string MenuItem1_3 {
            get {
                return ResourceManager.GetString("MenuItem1_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chicken Samosa.
        /// </summary>
        public static string MenuItem1_4 {
            get {
                return ResourceManager.GetString("MenuItem1_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onion Bhaji(Pakora).
        /// </summary>
        public static string MenuItem1_5 {
            get {
                return ResourceManager.GetString("MenuItem1_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potatoes (Pakora).
        /// </summary>
        public static string MenuItem1_5a {
            get {
                return ResourceManager.GetString("MenuItem1_5a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chicken Pakora.
        /// </summary>
        public static string MenuItem1_6 {
            get {
                return ResourceManager.GetString("MenuItem1_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to King Prawn Pakora.
        /// </summary>
        public static string MenuItem1_7 {
            get {
                return ResourceManager.GetString("MenuItem1_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fish Pakora.
        /// </summary>
        public static string MenuItem1_7a {
            get {
                return ResourceManager.GetString("MenuItem1_7a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tandoori Chicken.
        /// </summary>
        public static string MenuItem1_8 {
            get {
                return ResourceManager.GetString("MenuItem1_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vegetarian - Vegetarian.
        /// </summary>
        public static string MenuItem10 {
            get {
                return ResourceManager.GetString("MenuItem10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Butter Paneer.
        /// </summary>
        public static string MenuItem10_1 {
            get {
                return ResourceManager.GetString("MenuItem10_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mix Daal.
        /// </summary>
        public static string MenuItem10_2 {
            get {
                return ResourceManager.GetString("MenuItem10_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palak Paneer.
        /// </summary>
        public static string MenuItem10_3 {
            get {
                return ResourceManager.GetString("MenuItem10_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mix Veg.
        /// </summary>
        public static string MenuItem10_4 {
            get {
                return ResourceManager.GetString("MenuItem10_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aloofry Spicy.
        /// </summary>
        public static string MenuItem10_5 {
            get {
                return ResourceManager.GetString("MenuItem10_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spinach Potatoes.
        /// </summary>
        public static string MenuItem10_6 {
            get {
                return ResourceManager.GetString("MenuItem10_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allo Mutar.
        /// </summary>
        public static string MenuItem10_7 {
            get {
                return ResourceManager.GetString("MenuItem10_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The North Indian Special Dish.
        /// </summary>
        public static string MenuItem11 {
            get {
                return ResourceManager.GetString("MenuItem11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chicken Chilli.
        /// </summary>
        public static string MenuItem11_1 {
            get {
                return ResourceManager.GetString("MenuItem11_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lumb Chilli.
        /// </summary>
        public static string MenuItem11_1a {
            get {
                return ResourceManager.GetString("MenuItem11_1a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheese Chilli Veg.
        /// </summary>
        public static string MenuItem11_2 {
            get {
                return ResourceManager.GetString("MenuItem11_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fish Curry.
        /// </summary>
        public static string MenuItem11_3 {
            get {
                return ResourceManager.GetString("MenuItem11_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lamb Rogan Josh.
        /// </summary>
        public static string MenuItem11_4 {
            get {
                return ResourceManager.GetString("MenuItem11_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lamb Korma Creamy.
        /// </summary>
        public static string MenuItem11_5 {
            get {
                return ResourceManager.GetString("MenuItem11_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chicken Korma Creamy.
        /// </summary>
        public static string MenuItem11_5a {
            get {
                return ResourceManager.GetString("MenuItem11_5a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creamy Chicken.
        /// </summary>
        public static string MenuItem11_7 {
            get {
                return ResourceManager.GetString("MenuItem11_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naan Bread.
        /// </summary>
        public static string MenuItem12 {
            get {
                return ResourceManager.GetString("MenuItem12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plain Naan.
        /// </summary>
        public static string MenuItem12_1 {
            get {
                return ResourceManager.GetString("MenuItem12_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garlic Naan.
        /// </summary>
        public static string MenuItem12_2 {
            get {
                return ResourceManager.GetString("MenuItem12_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Butter Naan.
        /// </summary>
        public static string MenuItem12_3 {
            get {
                return ResourceManager.GetString("MenuItem12_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapati 2stk..
        /// </summary>
        public static string MenuItem12_4 {
            get {
                return ResourceManager.GetString("MenuItem12_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dessert.
        /// </summary>
        public static string MenuItem13 {
            get {
                return ResourceManager.GetString("MenuItem13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gulab Jamun.
        /// </summary>
        public static string MenuItem13_1 {
            get {
                return ResourceManager.GetString("MenuItem13_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drinks.
        /// </summary>
        public static string MenuItem14 {
            get {
                return ResourceManager.GetString("MenuItem14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mango Juice.
        /// </summary>
        public static string MenuItem14_1 {
            get {
                return ResourceManager.GetString("MenuItem14_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mango Lassi.
        /// </summary>
        public static string MenuItem14_2 {
            get {
                return ResourceManager.GetString("MenuItem14_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aqua D´or Natural or citrus.
        /// </summary>
        public static string MenuItem14_3 {
            get {
                return ResourceManager.GetString("MenuItem14_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to King Fisher (Indian beer).
        /// </summary>
        public static string MenuItem14_4 {
            get {
                return ResourceManager.GetString("MenuItem14_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cobra (Indian beer).
        /// </summary>
        public static string MenuItem14_5 {
            get {
                return ResourceManager.GetString("MenuItem14_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House Red Wine / White Wine.
        /// </summary>
        public static string MenuItem14_6 {
            get {
                return ResourceManager.GetString("MenuItem14_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alcohol-free Beer.
        /// </summary>
        public static string MenuItem14_7 {
            get {
                return ResourceManager.GetString("MenuItem14_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ginger Beer.
        /// </summary>
        public static string MenuItem14_8 {
            get {
                return ResourceManager.GetString("MenuItem14_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cola, Zero, Fanta, Faxe Kondi, Scweppes lemon.
        /// </summary>
        public static string MenuItem14_9 {
            get {
                return ResourceManager.GetString("MenuItem14_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessories.
        /// </summary>
        public static string MenuItem15 {
            get {
                return ResourceManager.GetString("MenuItem15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chutney Free choice.
        /// </summary>
        public static string MenuItem15_1 {
            get {
                return ResourceManager.GetString("MenuItem15_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Punjabi Thali Free Choice..
        /// </summary>
        public static string MenuItem16 {
            get {
                return ResourceManager.GetString("MenuItem16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cholle Naan.
        /// </summary>
        public static string MenuItem16_1 {
            get {
                return ResourceManager.GetString("MenuItem16_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cholle Poori.
        /// </summary>
        public static string MenuItem16_2 {
            get {
                return ResourceManager.GetString("MenuItem16_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cholle Bhatura.
        /// </summary>
        public static string MenuItem16_3 {
            get {
                return ResourceManager.GetString("MenuItem16_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lactose-free dishes.
        /// </summary>
        public static string MenuItem17 {
            get {
                return ResourceManager.GetString("MenuItem17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These dishes can be obtained lactose-free with rice.
        /// </summary>
        public static string MenuItem17_1 {
            get {
                return ResourceManager.GetString("MenuItem17_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Biryani.
        /// </summary>
        public static string MenuItem18 {
            get {
                return ResourceManager.GetString("MenuItem18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vegetarian Biryani.
        /// </summary>
        public static string MenuItem18_1 {
            get {
                return ResourceManager.GetString("MenuItem18_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chicken Biryani.
        /// </summary>
        public static string MenuItem18_2 {
            get {
                return ResourceManager.GetString("MenuItem18_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lamb Biyani.
        /// </summary>
        public static string MenuItem18_3 {
            get {
                return ResourceManager.GetString("MenuItem18_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to King Prawn Biryani.
        /// </summary>
        public static string MenuItem18_4 {
            get {
                return ResourceManager.GetString("MenuItem18_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to North India Pulao.
        /// </summary>
        public static string MenuItem18_5 {
            get {
                return ResourceManager.GetString("MenuItem18_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veg Pulao.
        /// </summary>
        public static string MenuItem18_5a {
            get {
                return ResourceManager.GetString("MenuItem18_5a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rice.
        /// </summary>
        public static string MenuItem18_6 {
            get {
                return ResourceManager.GetString("MenuItem18_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soup.
        /// </summary>
        public static string MenuItem2 {
            get {
                return ResourceManager.GetString("MenuItem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chicken Soup.
        /// </summary>
        public static string MenuItem2_1 {
            get {
                return ResourceManager.GetString("MenuItem2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daal Soup (Lentils).
        /// </summary>
        public static string MenuItem2_2 {
            get {
                return ResourceManager.GetString("MenuItem2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomato Soup.
        /// </summary>
        public static string MenuItem2_3 {
            get {
                return ResourceManager.GetString("MenuItem2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salads.
        /// </summary>
        public static string MenuItem3 {
            get {
                return ResourceManager.GetString("MenuItem3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The North Indian Salad.
        /// </summary>
        public static string MenuItem3_1 {
            get {
                return ResourceManager.GetString("MenuItem3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veg Cheese Salad.
        /// </summary>
        public static string MenuItem3_2 {
            get {
                return ResourceManager.GetString("MenuItem3_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yogurt.
        /// </summary>
        public static string MenuItem4 {
            get {
                return ResourceManager.GetString("MenuItem4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raita (Yogurt).
        /// </summary>
        public static string MenuItem4_1 {
            get {
                return ResourceManager.GetString("MenuItem4_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boondi Raita.
        /// </summary>
        public static string MenuItem4_2 {
            get {
                return ResourceManager.GetString("MenuItem4_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biryani including Boondi Raita.
        /// </summary>
        public static string MenuItem4_3 {
            get {
                return ResourceManager.GetString("MenuItem4_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Butter Dishes.
        /// </summary>
        public static string MenuItem5 {
            get {
                return ResourceManager.GetString("MenuItem5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Butter Chicken.
        /// </summary>
        public static string MenuItem5_1 {
            get {
                return ResourceManager.GetString("MenuItem5_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Butter Beef.
        /// </summary>
        public static string MenuItem5_2 {
            get {
                return ResourceManager.GetString("MenuItem5_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Butter Lam.
        /// </summary>
        public static string MenuItem5_3 {
            get {
                return ResourceManager.GetString("MenuItem5_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Butter King Prawn.
        /// </summary>
        public static string MenuItem5_4 {
            get {
                return ResourceManager.GetString("MenuItem5_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children&apos;&apos;s menu.
        /// </summary>
        public static string MenuItem6_1 {
            get {
                return ResourceManager.GetString("MenuItem6_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuggets and Fries.
        /// </summary>
        public static string MenuItem6_2 {
            get {
                return ResourceManager.GetString("MenuItem6_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fish fillet and fries.
        /// </summary>
        public static string MenuItem6_3 {
            get {
                return ResourceManager.GetString("MenuItem6_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curry Dishes.
        /// </summary>
        public static string MenuItem7 {
            get {
                return ResourceManager.GetString("MenuItem7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chicken Curry.
        /// </summary>
        public static string MenuItem7_1 {
            get {
                return ResourceManager.GetString("MenuItem7_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beef Curry.
        /// </summary>
        public static string MenuItem7_2 {
            get {
                return ResourceManager.GetString("MenuItem7_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lamb Curry.
        /// </summary>
        public static string MenuItem7_3 {
            get {
                return ResourceManager.GetString("MenuItem7_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to King Prawn.
        /// </summary>
        public static string MenuItem7_4 {
            get {
                return ResourceManager.GetString("MenuItem7_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fish Carry.
        /// </summary>
        public static string MenuItem7_4a {
            get {
                return ResourceManager.GetString("MenuItem7_4a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tikka Masala Dishes.
        /// </summary>
        public static string MenuItem8 {
            get {
                return ResourceManager.GetString("MenuItem8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chicken Tikka Masala.
        /// </summary>
        public static string MenuItem8_1 {
            get {
                return ResourceManager.GetString("MenuItem8_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beef Tikka Masala.
        /// </summary>
        public static string MenuItem8_2 {
            get {
                return ResourceManager.GetString("MenuItem8_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lamb Tikka Masala.
        /// </summary>
        public static string MenuItem8_3 {
            get {
                return ResourceManager.GetString("MenuItem8_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to King Prawn Tikka Masala.
        /// </summary>
        public static string MenuItem8_4 {
            get {
                return ResourceManager.GetString("MenuItem8_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spinach (Palak) Dishes.
        /// </summary>
        public static string MenuItem9 {
            get {
                return ResourceManager.GetString("MenuItem9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spinach (Palak) chicken.
        /// </summary>
        public static string MenuItem9_1 {
            get {
                return ResourceManager.GetString("MenuItem9_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spinach Ox.
        /// </summary>
        public static string MenuItem9_2 {
            get {
                return ResourceManager.GetString("MenuItem9_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spinach (Palak) lamb.
        /// </summary>
        public static string MenuItem9_3 {
            get {
                return ResourceManager.GetString("MenuItem9_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spinach (Palak) King Prawn.
        /// </summary>
        public static string MenuItem9_4 {
            get {
                return ResourceManager.GetString("MenuItem9_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string MenuQuantity {
            get {
                return ResourceManager.GetString("MenuQuantity", resourceCulture);
            }
        }
    }
}
